// Matching vocabulary only. Approved bilingual product pairs from issue #267.
export const shoppingCatalog = [
  { en: "Pineapple", no: "Ananas" },
  { en: "Apricot", no: "Aprikos" },
  { en: "Artichokes", no: "Artisjokk" },
  { en: "Eggplant", no: "Aubergine" },
  { en: "Avocado", no: "Avocado" },
  { en: "Bananas", no: "Bananer" },
  { en: "Basil", no: "Basilikum" },
  { en: "Berries", no: "Bær" },
  { en: "Pears", no: "Pære" },
  { en: "Cauliflower", no: "Blomkål" },
  { en: "Broccoli", no: "Brokkoli" },
  { en: "Blackberries", no: "Bjørnebær" },
  { en: "Cherry tomatoes", no: "Cherrytomater" },
  { en: "Dates", no: "Dadler" },
  { en: "Peas", no: "Erter" },
  { en: "Strawberries", no: "Jordbær" },
  { en: "Figs", no: "Fiken" },
  { en: "Fennel", no: "Fennikel" },
  { en: "Fruit", no: "Frukt" },
  { en: "Scallions", no: "Vårløk" },
  { en: "Vegetables", no: "Grønnsaker" },
  { en: "Grapefruit", no: "Grapefrukt" },
  { en: "Cucumber", no: "Agurk" },
  { en: "Blueberries", no: "Blåbær" },
  { en: "Raspberries", no: "Bringebær" },
  { en: "Ginger", no: "Ingefær" },
  { en: "Carrots", no: "Gulrot" },
  { en: "Potatoes", no: "Potet" },
  { en: "Cherries", no: "Kirsebær" },
  { en: "Kiwis", no: "Kiwi" },
  { en: "Garlic", no: "Hvitløk" },
  { en: "Cabbage", no: "Hodekål" },
  { en: "Cilantro", no: "Koriander" },
  { en: "Herbs", no: "Urter" },
  { en: "Squash", no: "Gresskar" },
  { en: "Lettuce", no: "Bladsalat" },
  { en: "Leek", no: "Purre" },
  { en: "Lime", no: "Lime" },
  { en: "Sweet corn", no: "Mais" },
  { en: "Mandarins", no: "Klementin" },
  { en: "Mango", no: "Mango" },
  { en: "Melon", no: "Melon" },
  { en: "Cranberries", no: "Tranebær" },
  { en: "Nectarine", no: "Nektarin" },
  { en: "Olives", no: "Oliven" },
  { en: "Orange", no: "Appelsin" },
  { en: "Passion fruit", no: "Pasjonsfrukt" },
  { en: "Chillies", no: "Chillipepper" },
  { en: "Bell pepper", no: "Paprika" },
  { en: "Parsley", no: "Persille" },
  { en: "Mint", no: "Peppermynte" },
  { en: "Peach", no: "Fersken" },
  { en: "Prunes", no: "Plommer" },
  { en: "Mushrooms", no: "Sopp" },
  { en: "Radish", no: "Reddik" },
  { en: "Rhubarb", no: "Rabarbra" },
  { en: "Beets", no: "Rødbeter" },
  { en: "Arugula", no: "Ruccola" },
  { en: "Salad", no: "Salat" },
  { en: "Sage", no: "Salvie" },
  { en: "Chives", no: "Gressløk" },
  { en: "Celery", no: "Stangselleri" },
  { en: "Asparagus", no: "Asparges" },
  { en: "Spinach", no: "Spinat" },
  { en: "Thyme", no: "Timian" },
  { en: "Tomatoes", no: "Tomat" },
  { en: "Grapes", no: "Druer" },
  { en: "Watermelon", no: "Vannmelon" },
  { en: "Lemon", no: "Sitron" },
  { en: "Zucchini", no: "Squash" },
  { en: "Onions", no: "Løk" },
  { en: "Sun-dried tomatoes", no: "Soltørkede tomater" },
  { en: "Apples", no: "Epler" },
  { en: "Sweet Potatoes", no: "Søtpotet" },
  { en: "Bagels", no: "Bagel" },
  { en: "Baguette", no: "Baguette" },
  { en: "Puff pastry", no: "Butterdeig" },
  { en: "Bread", no: "Brød" },
  { en: "Sliced bread", no: "Oppskåret brød" },
  { en: "Buns", no: "Boller" },
  { en: "Donuts", no: "Smultringer" },
  { en: "Croissant", no: "Croissant" },
  { en: "Crispbread", no: "Knekkebrød" },
  { en: "Muffins", no: "Muffins" },
  { en: "Pancakes mix", no: "Pannekakemiks" },
  { en: "Pie", no: "Pai" },
  { en: "Pizza dough", no: "Pizzadeig" },
  { en: "Scones", no: "Scones" },
  { en: "Rolls", no: "Rundstykker" },
  { en: "Toast", no: "Ristet brød" },
  { en: "Tortillas", no: "Tortilla" },
  { en: "Waffles", no: "Vaffel" },
  { en: "Pumpkin Pie", no: "Gresskarpai" },
  { en: "Dinner Rolls", no: "Middagsrundstykker" },
  { en: "Blue cheese", no: "Blåmuggost" },
  { en: "Butter", no: "Smør" },
  { en: "Cheddar", no: "Cheddar" },
  { en: "Creme fraiche", no: "Crème fraîche" },
  { en: "Eggs", no: "Egg" },
  { en: "Feta", no: "Fetaost" },
  { en: "Cream cheese", no: "Smøreost" },
  { en: "Gorgonzola", no: "Gorgonzola" },
  { en: "Cottage cheese", no: "Cottage cheese" },
  { en: "Yogurt", no: "Yoghurt" },
  { en: "Cheese", no: "Ost" },
  { en: "Margarine", no: "Margarin" },
  { en: "Mascarpone", no: "Mascarpone" },
  { en: "Milk", no: "Melk" },
  { en: "Mozzarella", no: "Mozzarella" },
  { en: "Parmesan", no: "Parmesan" },
  { en: "Quark", no: "Kvarg" },
  { en: "Cream", no: "Fløte" },
  { en: "Grated cheese", no: "Revet ost" },
  { en: "Ricotta", no: "Ricotta" },
  { en: "Sour cream", no: "Rømme" },
  { en: "Soy Milk", no: "Soyamelk" },
  { en: "Brown cheese", no: "Brunost" },
  { en: "Cultured milk", no: "Surmelk" },
  { en: "Cold cuts", no: "Kjøttpålegg" },
  { en: "Oysters", no: "Østers" },
  { en: "Bratwurst", no: "Bratwurst" },
  { en: "Fish", no: "Fisk" },
  { en: "Meat", no: "Kjøtt" },
  { en: "Shrimp", no: "Reker" },
  { en: "Ground meat", no: "Kjøttdeig" },
  { en: "Hot Dog", no: "Grillpølser" },
  { en: "Lobster", no: "Hummer" },
  { en: "Veal", no: "Kalvekjøtt" },
  { en: "Salmon", no: "Laks" },
  { en: "Lamb", no: "Lammekjøtt" },
  { en: "Mussels", no: "Blåskjell" },
  { en: "Chicken", no: "Kylling" },
  { en: "Chicken breast", no: "Kyllingbryst" },
  { en: "Turkey breast", no: "Kalkunbryst" },
  { en: "Beef", no: "Storfekjøtt" },
  { en: "Sliced beef", no: "Biffstrimler" },
  { en: "Prosciutto", no: "Prosciutto" },
  { en: "Salami", no: "Salami" },
  { en: "Anchovies", no: "Ansjos" },
  { en: "Ham", no: "Skinke" },
  { en: "Pork", no: "Svinekjøtt" },
  { en: "Bacon", no: "Bacon" },
  { en: "Steak", no: "Biff" },
  { en: "Tuna", no: "Tunfisk" },
  { en: "Turkey", no: "Kalkun" },
  { en: "Sausage", no: "Kjøttpølse" },
  { en: "Sausages", no: "Pølser" },
  { en: "Cured meat", no: "Spekekjøtt" },
  { en: "Fish cakes", no: "Fiskekaker" },
  { en: "Smoked salmon", no: "Røkt laks" },
  { en: "Caviar", no: "Kaviar" },
  { en: "Maple syrup", no: "Lønnesirup" },
  { en: "Apple sauce", no: "Eplemos" },
  { en: "BBQ sauce", no: "BBQ-saus" },
  { en: "Baking powder", no: "Bakepulver" },
  { en: "Balsamic vinegar", no: "Balsamico eddik" },
  { en: "Walnuts", no: "Valnøtter" },
  { en: "Baking soda", no: "Natron" },
  { en: "Beans", no: "Bønner" },
  { en: "Stock", no: "Buljong" },
  { en: "Gravy", no: "Saus" },
  { en: "Chutney", no: "Chutney" },
  { en: "Dip", no: "Dip" },
  { en: "Peanut butter", no: "Peanøttsmør" },
  { en: "Vinegar", no: "Eddik" },
  { en: "Hazelnuts", no: "Hasselnøtter" },
  { en: "Yeast", no: "Gjær" },
  { en: "Ketchup", no: "Ketchup" },
  { en: "Coconut milk", no: "Kokosmelk" },
  { en: "Lentils", no: "Linser" },
  { en: "Almonds", no: "Mandler" },
  { en: "Mayonnaise", no: "Majones" },
  { en: "Nuts", no: "Nøtter" },
  { en: "Olive oil", no: "Olivenolje" },
  { en: "Oregano", no: "Oregano" },
  { en: "Breadcrumbs", no: "Strøkavring" },
  { en: "Paprika", no: "Paprikapulver" },
  { en: "Pasta sauce", no: "Pastasaus" },
  { en: "Canned tomatoes", no: "Hermetiske tomater" },
  { en: "Peppercorns", no: "Hel sort pepper" },
  { en: "Black Pepper", no: "Svart pepper" },
  { en: "Pine nuts", no: "Pinjekjerner" },
  { en: "Icing sugar", no: "Melis" },
  { en: "Rosemary", no: "Rosmarin" },
  { en: "Salad dressing", no: "Dressing" },
  { en: "Salt", no: "Salt" },
  { en: "Hot sauce", no: "Chillisaus" },
  { en: "Mustard", no: "Sennep" },
  { en: "Soy sauce", no: "Soyasaus" },
  { en: "Cornflour", no: "Maisstivelse" },
  { en: "Tomato purée", no: "Tomatpurré" },
  { en: "Tomato sauce", no: "Tomatsaus" },
  { en: "Vanilla", no: "Vaniljesukker" },
  { en: "Cinnamon", no: "Kanel" },
  { en: "Sugar", no: "Sukker" },
  { en: "Oil", no: "Olje" },
  { en: "Cranberry Sauce", no: "Tranebærsaus" },
  { en: "Mashed Potatoes", no: "Potetmos" },
  { en: "Cornbread Stuffing", no: "Maisbrødfyll" },
  { en: "Pickles", no: "Sylteagurk" },
  { en: "Baked Beans", no: "Hermetiske bønner" },
  { en: "Burritos", no: "Burritos" },
  { en: "Chicken Wings", no: "Kyllingvinger" },
  { en: "Chinese food", no: "Kinesisk ferdigmat" },
  { en: "Fish sticks", no: "Fiskepinner" },
  { en: "Frozen vegetables", no: "Frosne grønnsaker" },
  { en: "Ice cream", no: "Iskrem" },
  { en: "Indian food", no: "Indisk ferdigmat" },
  { en: "Italian food", no: "Italiensk ferdigmat" },
  { en: "Dumplings", no: "Dumplings" },
  { en: "Lasagna", no: "Lasagne" },
  { en: "Mexican food", no: "Meksikansk ferdigmat" },
  { en: "Pizza", no: "Pizza" },
  { en: "French fries", no: "Pommes frites" },
  { en: "Soup", no: "Suppe" },
  { en: "TV dinner", no: "Ferdigmiddag" },
  { en: "Thai food", no: "Thai ferdigmat" },
  { en: "Sour cream porridge", no: "Rømmegrøt" },
  { en: "Taco", no: "Taco" },
  { en: "Basmati rice", no: "Basmatiris" },
  { en: "Corn flakes", no: "Corn Flakes" },
  { en: "Couscous", no: "Couscous" },
  { en: "Cereal", no: "Frokostblanding" },
  { en: "Semolina", no: "Semulegryn" },
  { en: "Oatmeal", no: "Havregryn" },
  { en: "Chickpeas", no: "Kikerter" },
  { en: "Flour", no: "Mel" },
  { en: "Muesli", no: "Müsli" },
  { en: "Pasta", no: "Pasta" },
  { en: "Noodles", no: "Nudler" },
  { en: "Penne", no: "Pasta penne" },
  { en: "Rice", no: "Ris" },
  { en: "Risotto rice", no: "Risottoris" },
  { en: "Spaghetti", no: "Spaghetti" },
  { en: "Tofu", no: "Tofu" },
  { en: "Wild rice", no: "Villris" },
  { en: "Pretzels", no: "Saltstenger" },
  { en: "Dessert", no: "Dessert" },
  { en: "Dried fruit", no: "Tørket frukt" },
  { en: "Peanuts", no: "Peanøtter" },
  { en: "Jello", no: "Gelé" },
  { en: "Cereal bar", no: "Müslibar" },
  { en: "Christmas cookies", no: "Julekaker" },
  { en: "Honey", no: "Honning" },
  { en: "Chewing gum", no: "Tyggegummi" },
  { en: "Cookies", no: "Cookies" },
  { en: "Jam", no: "Syltetøy" },
  { en: "Crackers", no: "Kjeks" },
  { en: "Cake", no: "Kake" },
  { en: "Gingerbread", no: "Pepperkaker" },
  { en: "Marshmallows", no: "Marshmallows" },
  { en: "Nougat cream", no: "Nougatkrem" },
  { en: "Chips", no: "Potetgull" },
  { en: "Pop corn", no: "Popkorn" },
  { en: "Chocolate", no: "Sjokolade" },
  { en: "Snacks", no: "Snacks" },
  { en: "Candy", no: "Sukkertøy" },
  { en: "Tortilla Chips", no: "Tortillachips" },
  { en: "Vanilla sauce", no: "Vaniljesaus" },
  { en: "Apple juice", no: "Eplejuice" },
  { en: "Beer", no: "Øl" },
  { en: "Champagne", no: "Champagne" },
  { en: "Cider", no: "Sider" },
  { en: "Cola", no: "Coca Cola" },
  { en: "Diet Cola", no: "Cola light" },
  { en: "Iced tea", no: "Iste" },
  { en: "Energy drink", no: "Energidrikk" },
  { en: "Fruit juice", no: "Juice" },
  { en: "Beverages", no: "Drikkevarer" },
  { en: "Gin", no: "Gin" },
  { en: "Ginger Ale", no: "Ingefærøl" },
  { en: "Coffee", no: "Kaffe" },
  { en: "Coffee beans", no: "Kaffebønner" },
  { en: "Coffee pads", no: "Kaffeputer" },
  { en: "Coffee capsules", no: "Kaffekapsler" },
  { en: "Hot chocolate", no: "Kakao" },
  { en: "Diet soda", no: "Lettbrus" },
  { en: "Soda", no: "Brus" },
  { en: "Bottled water", no: "Mineralvann" },
  { en: "Orange juice", no: "Appelsinjuice" },
  { en: "Prosecco", no: "Prosecco" },
  { en: "Red wine", no: "Rødvin" },
  { en: "Rum", no: "Rom" },
  { en: "Spirits", no: "Sprit" },
  { en: "Smoothie", no: "Smoothie" },
  { en: "Sports drink", no: "Sportsdrikk" },
  { en: "Tea", no: "Te" },
  { en: "Tonic Water", no: "Tonic" },
  { en: "Vodka", no: "Vodka" },
  { en: "Water", no: "Vann" },
  { en: "White wine", no: "Hvitvin" },
  { en: "Whiskey", no: "Whisky" },
  { en: "Cigarettes", no: "Sigaretter" },
  { en: "Ale", no: "Ale" },
  { en: "Garbage bags", no: "Avfallsposer" },
  { en: "Dishwashing liquid", no: "Oppvaskmiddel" },
  { en: "Aluminum foil", no: "Aluminiumsfolie" },
  { en: "Baby food", no: "Babymat" },
  { en: "Parchment paper", no: "Bakepapir" },
  {
    en: "Bathroom cleaner",
    no: "Rengjøringsmiddel bad",
  },
  { en: "Batteries", no: "Batterier" },
  { en: "Flowers", no: "Blomster" },
  { en: "Plastic wrap", no: "Plastfolie" },
  { en: "Gift", no: "Gave" },
  { en: "Wrapping paper", no: "Gavepapir" },
  { en: "Dishwasher salt", no: "Oppvaskmaskinsalt" },
  {
    en: "Dishwasher tabs",
    no: "Oppvaskmaskintabletter",
  },
  { en: "Glass cleaner", no: "Glassrens" },
  { en: "Light bulb", no: "Lyspærer" },
  { en: "Paper towels", no: "Tørkepapir" },
  { en: "Candles", no: "Stearinlys" },
  { en: "Cleaning supplies", no: "Rengjøringsmiddel" },
  { en: "Sponge", no: "Svamp" },
  { en: "Napkins", no: "Servitter" },
  { en: "Toilet cleaner", no: "WC-rens" },
  { en: "Laundry detergent", no: "Vaskemiddel" },
  { en: "Fabric softener", no: "Tøymykner" },
  { en: "Pads", no: "Bind" },
  { en: "Body lotion", no: "Fuktighetskrem" },
  { en: "Conditioner", no: "Balsam" },
  { en: "Deodorant", no: "Deodorant" },
  { en: "Shower gel", no: "Dusjsåpe" },
  { en: "Wet wipes", no: "Våtservitter" },
  { en: "Face cream", no: "Ansiktskrem" },
  { en: "Hair gel", no: "Hårgelé" },
  { en: "Hair spray", no: "Hårspray" },
  { en: "Hand cream", no: "Håndkrem" },
  { en: "Insect Repellent", no: "Insektsmiddel" },
  { en: "Condoms", no: "Kondomer" },
  { en: "Facial tissues", no: "Ansiktsservietter" },
  { en: "Contact lens solution", no: "Kontaktlinsevæske" },
  { en: "Lip balm", no: "Leppepomade" },
  { en: "Makeup remover", no: "Sminkefjerner" },
  { en: "Mouthwash", no: "Munnskyll" },
  { en: "Nail polish", no: "Neglelakk" },
  { en: "Nail polish remover", no: "Neglelakkfjerner" },
  { en: "Bandaids", no: "Plaster" },
  { en: "Razor", no: "Barberhøvel" },
  { en: "Razor blades", no: "Barberblader" },
  { en: "Shaving cream", no: "Barberskum" },
  { en: "Pain reliever", no: "Smertestillende" },
  { en: "Soap", no: "Såpe" },
  { en: "Shampoo", no: "Shampo" },
  { en: "Sunblock", no: "Solkrem" },
  { en: "Tampons", no: "Tamponger" },
  { en: "Tissues", no: "Papirlommetørkle" },
  { en: "Vitamins", no: "Vitaminer" },
  { en: "Toilet paper", no: "Dopapir" },
  { en: "Cotton pads", no: "Bomullspads" },
  { en: "Cotton swabs", no: "Bomullspinner" },
  { en: "Diapers", no: "Bleier" },
  { en: "Toothbrush", no: "Tannbørste" },
  { en: "Toothpaste", no: "Tannkrem" },
  { en: "Dental floss", no: "Tanntråd" },
  { en: "Cod liver oil", no: "Tran" },
  { en: "Fish food", no: "Fiskemat" },
  { en: "Dog food", no: "Hundemat" },
  { en: "Dog treats", no: "Hundegodt" },
  { en: "Cat food", no: "Kattemat" },
  { en: "Cat treats", no: "Kattegodt" },
  { en: "Cat litter", no: "Kattesand" },
  { en: "Bird food", no: "Fuglemat" },
  { en: "Potting soil", no: "Blomsterjord" },
  { en: "Grill", no: "Grill" },
  { en: "Parasol", no: "Parasoll" },
  { en: "Fertilizer", no: "Gjødsel" },
  { en: "Pots", no: "Potter" },
  { en: "Garden tool", no: "Hageredskap" },
  { en: "Seeds", no: "Frø" },
  { en: "Propane", no: "Propan" },
  { en: "Charcoal", no: "Kull" },
  { en: "Nails", no: "Spiker" },
  { en: "Bolts", no: "Bolter" },
  { en: "Brush", no: "Pensel" },
  { en: "Watering can", no: "Vannkanne" },
  { en: "Plants", no: "Planter" },
  { en: "Lawnmower", no: "Gressklipper" },
] satisfies { en: string; no: string }[];
