CREATE TYPE "ShoppingCategory" AS ENUM ('PRODUCE', 'BAKERY', 'DAIRY', 'MEAT', 'INGREDIENTS', 'FROZEN', 'GRAINS', 'SNACKS', 'BEVERAGES', 'HOUSEHOLD', 'CARE', 'PETS', 'GARDEN', 'OWN_ITEMS');

ALTER TABLE "ShoppingProduct" ADD COLUMN "category" "ShoppingCategory";

-- Freeze the initial English vocabulary for existing names across all collections.
WITH catalog(name, category) AS (VALUES
  ('pineapple', 'PRODUCE'),
  ('apricot', 'PRODUCE'),
  ('artichokes', 'PRODUCE'),
  ('eggplant', 'PRODUCE'),
  ('avocado', 'PRODUCE'),
  ('bananas', 'PRODUCE'),
  ('basil', 'PRODUCE'),
  ('berries', 'PRODUCE'),
  ('pears', 'PRODUCE'),
  ('cauliflower', 'PRODUCE'),
  ('broccoli', 'PRODUCE'),
  ('blackberries', 'PRODUCE'),
  ('cherry tomatoes', 'PRODUCE'),
  ('dates', 'PRODUCE'),
  ('peas', 'PRODUCE'),
  ('strawberries', 'PRODUCE'),
  ('figs', 'PRODUCE'),
  ('fennel', 'PRODUCE'),
  ('fruit', 'PRODUCE'),
  ('scallions', 'PRODUCE'),
  ('vegetables', 'PRODUCE'),
  ('grapefruit', 'PRODUCE'),
  ('cucumber', 'PRODUCE'),
  ('blueberries', 'PRODUCE'),
  ('raspberries', 'PRODUCE'),
  ('ginger', 'PRODUCE'),
  ('carrots', 'PRODUCE'),
  ('potatoes', 'PRODUCE'),
  ('cherries', 'PRODUCE'),
  ('kiwis', 'PRODUCE'),
  ('garlic', 'PRODUCE'),
  ('cabbage', 'PRODUCE'),
  ('cilantro', 'PRODUCE'),
  ('herbs', 'PRODUCE'),
  ('squash', 'PRODUCE'),
  ('lettuce', 'PRODUCE'),
  ('leek', 'PRODUCE'),
  ('lime', 'PRODUCE'),
  ('sweet corn', 'PRODUCE'),
  ('mandarins', 'PRODUCE'),
  ('mango', 'PRODUCE'),
  ('melon', 'PRODUCE'),
  ('cranberries', 'PRODUCE'),
  ('nectarine', 'PRODUCE'),
  ('olives', 'PRODUCE'),
  ('orange', 'PRODUCE'),
  ('passion fruit', 'PRODUCE'),
  ('chillies', 'PRODUCE'),
  ('bell pepper', 'PRODUCE'),
  ('parsley', 'PRODUCE'),
  ('mint', 'PRODUCE'),
  ('peach', 'PRODUCE'),
  ('prunes', 'PRODUCE'),
  ('mushrooms', 'PRODUCE'),
  ('radish', 'PRODUCE'),
  ('rhubarb', 'PRODUCE'),
  ('beets', 'PRODUCE'),
  ('arugula', 'PRODUCE'),
  ('salad', 'PRODUCE'),
  ('sage', 'PRODUCE'),
  ('chives', 'PRODUCE'),
  ('celery', 'PRODUCE'),
  ('asparagus', 'PRODUCE'),
  ('spinach', 'PRODUCE'),
  ('thyme', 'PRODUCE'),
  ('tomatoes', 'PRODUCE'),
  ('grapes', 'PRODUCE'),
  ('watermelon', 'PRODUCE'),
  ('lemon', 'PRODUCE'),
  ('zucchini', 'PRODUCE'),
  ('onions', 'PRODUCE'),
  ('sun-dried tomatoes', 'PRODUCE'),
  ('apples', 'PRODUCE'),
  ('sweet potatoes', 'PRODUCE'),
  ('bagels', 'BAKERY'),
  ('baguette', 'BAKERY'),
  ('puff pastry', 'BAKERY'),
  ('bread', 'BAKERY'),
  ('sliced bread', 'BAKERY'),
  ('buns', 'BAKERY'),
  ('donuts', 'BAKERY'),
  ('croissant', 'BAKERY'),
  ('crispbread', 'BAKERY'),
  ('muffins', 'BAKERY'),
  ('pancakes mix', 'BAKERY'),
  ('pie', 'BAKERY'),
  ('pizza dough', 'BAKERY'),
  ('scones', 'BAKERY'),
  ('rolls', 'BAKERY'),
  ('toast', 'BAKERY'),
  ('tortillas', 'BAKERY'),
  ('waffles', 'BAKERY'),
  ('pumpkin pie', 'BAKERY'),
  ('dinner rolls', 'BAKERY'),
  ('blue cheese', 'DAIRY'),
  ('butter', 'DAIRY'),
  ('cheddar', 'DAIRY'),
  ('creme fraiche', 'DAIRY'),
  ('eggs', 'DAIRY'),
  ('feta', 'DAIRY'),
  ('cream cheese', 'DAIRY'),
  ('gorgonzola', 'DAIRY'),
  ('cottage cheese', 'DAIRY'),
  ('yogurt', 'DAIRY'),
  ('cheese', 'DAIRY'),
  ('margarine', 'DAIRY'),
  ('mascarpone', 'DAIRY'),
  ('milk', 'DAIRY'),
  ('mozzarella', 'DAIRY'),
  ('parmesan', 'DAIRY'),
  ('quark', 'DAIRY'),
  ('cream', 'DAIRY'),
  ('grated cheese', 'DAIRY'),
  ('ricotta', 'DAIRY'),
  ('sour cream', 'DAIRY'),
  ('soy milk', 'DAIRY'),
  ('brown cheese', 'DAIRY'),
  ('cultured milk', 'DAIRY'),
  ('cold cuts', 'MEAT'),
  ('oysters', 'MEAT'),
  ('bratwurst', 'MEAT'),
  ('fish', 'MEAT'),
  ('meat', 'MEAT'),
  ('shrimp', 'MEAT'),
  ('ground meat', 'MEAT'),
  ('hot dog', 'MEAT'),
  ('lobster', 'MEAT'),
  ('veal', 'MEAT'),
  ('salmon', 'MEAT'),
  ('lamb', 'MEAT'),
  ('mussels', 'MEAT'),
  ('chicken', 'MEAT'),
  ('chicken breast', 'MEAT'),
  ('turkey breast', 'MEAT'),
  ('beef', 'MEAT'),
  ('sliced beef', 'MEAT'),
  ('prosciutto', 'MEAT'),
  ('salami', 'MEAT'),
  ('anchovies', 'MEAT'),
  ('ham', 'MEAT'),
  ('pork', 'MEAT'),
  ('bacon', 'MEAT'),
  ('steak', 'MEAT'),
  ('tuna', 'MEAT'),
  ('turkey', 'MEAT'),
  ('sausage', 'MEAT'),
  ('sausages', 'MEAT'),
  ('cured meat', 'MEAT'),
  ('fish cakes', 'MEAT'),
  ('smoked salmon', 'MEAT'),
  ('caviar', 'MEAT'),
  ('maple syrup', 'INGREDIENTS'),
  ('apple sauce', 'INGREDIENTS'),
  ('bbq sauce', 'INGREDIENTS'),
  ('baking powder', 'INGREDIENTS'),
  ('balsamic vinegar', 'INGREDIENTS'),
  ('walnuts', 'INGREDIENTS'),
  ('baking soda', 'INGREDIENTS'),
  ('beans', 'INGREDIENTS'),
  ('stock', 'INGREDIENTS'),
  ('gravy', 'INGREDIENTS'),
  ('chutney', 'INGREDIENTS'),
  ('dip', 'INGREDIENTS'),
  ('peanut butter', 'INGREDIENTS'),
  ('vinegar', 'INGREDIENTS'),
  ('hazelnuts', 'INGREDIENTS'),
  ('yeast', 'INGREDIENTS'),
  ('ketchup', 'INGREDIENTS'),
  ('coconut milk', 'INGREDIENTS'),
  ('lentils', 'INGREDIENTS'),
  ('almonds', 'INGREDIENTS'),
  ('mayonnaise', 'INGREDIENTS'),
  ('nuts', 'INGREDIENTS'),
  ('olive oil', 'INGREDIENTS'),
  ('oregano', 'INGREDIENTS'),
  ('breadcrumbs', 'INGREDIENTS'),
  ('paprika', 'INGREDIENTS'),
  ('pasta sauce', 'INGREDIENTS'),
  ('canned tomatoes', 'INGREDIENTS'),
  ('peppercorns', 'INGREDIENTS'),
  ('black pepper', 'INGREDIENTS'),
  ('pine nuts', 'INGREDIENTS'),
  ('icing sugar', 'INGREDIENTS'),
  ('rosemary', 'INGREDIENTS'),
  ('salad dressing', 'INGREDIENTS'),
  ('salt', 'INGREDIENTS'),
  ('hot sauce', 'INGREDIENTS'),
  ('mustard', 'INGREDIENTS'),
  ('soy sauce', 'INGREDIENTS'),
  ('cornflour', 'INGREDIENTS'),
  ('tomato purée', 'INGREDIENTS'),
  ('tomato sauce', 'INGREDIENTS'),
  ('vanilla', 'INGREDIENTS'),
  ('cinnamon', 'INGREDIENTS'),
  ('sugar', 'INGREDIENTS'),
  ('oil', 'INGREDIENTS'),
  ('cranberry sauce', 'INGREDIENTS'),
  ('mashed potatoes', 'INGREDIENTS'),
  ('cornbread stuffing', 'INGREDIENTS'),
  ('pickles', 'INGREDIENTS'),
  ('baked beans', 'FROZEN'),
  ('burritos', 'FROZEN'),
  ('chicken wings', 'FROZEN'),
  ('chinese food', 'FROZEN'),
  ('fish sticks', 'FROZEN'),
  ('frozen vegetables', 'FROZEN'),
  ('ice cream', 'FROZEN'),
  ('indian food', 'FROZEN'),
  ('italian food', 'FROZEN'),
  ('dumplings', 'FROZEN'),
  ('lasagna', 'FROZEN'),
  ('mexican food', 'FROZEN'),
  ('pizza', 'FROZEN'),
  ('french fries', 'FROZEN'),
  ('soup', 'FROZEN'),
  ('tv dinner', 'FROZEN'),
  ('thai food', 'FROZEN'),
  ('sour cream porridge', 'FROZEN'),
  ('taco', 'FROZEN'),
  ('basmati rice', 'GRAINS'),
  ('corn flakes', 'GRAINS'),
  ('couscous', 'GRAINS'),
  ('cereal', 'GRAINS'),
  ('semolina', 'GRAINS'),
  ('oatmeal', 'GRAINS'),
  ('chickpeas', 'GRAINS'),
  ('flour', 'GRAINS'),
  ('muesli', 'GRAINS'),
  ('pasta', 'GRAINS'),
  ('noodles', 'GRAINS'),
  ('penne', 'GRAINS'),
  ('rice', 'GRAINS'),
  ('risotto rice', 'GRAINS'),
  ('spaghetti', 'GRAINS'),
  ('tofu', 'GRAINS'),
  ('wild rice', 'GRAINS'),
  ('pretzels', 'SNACKS'),
  ('dessert', 'SNACKS'),
  ('dried fruit', 'SNACKS'),
  ('peanuts', 'SNACKS'),
  ('jello', 'SNACKS'),
  ('cereal bar', 'SNACKS'),
  ('christmas cookies', 'SNACKS'),
  ('honey', 'SNACKS'),
  ('chewing gum', 'SNACKS'),
  ('cookies', 'SNACKS'),
  ('jam', 'SNACKS'),
  ('crackers', 'SNACKS'),
  ('cake', 'SNACKS'),
  ('gingerbread', 'SNACKS'),
  ('marshmallows', 'SNACKS'),
  ('nougat cream', 'SNACKS'),
  ('chips', 'SNACKS'),
  ('pop corn', 'SNACKS'),
  ('chocolate', 'SNACKS'),
  ('snacks', 'SNACKS'),
  ('candy', 'SNACKS'),
  ('tortilla chips', 'SNACKS'),
  ('vanilla sauce', 'SNACKS'),
  ('apple juice', 'BEVERAGES'),
  ('beer', 'BEVERAGES'),
  ('champagne', 'BEVERAGES'),
  ('cider', 'BEVERAGES'),
  ('cola', 'BEVERAGES'),
  ('diet cola', 'BEVERAGES'),
  ('iced tea', 'BEVERAGES'),
  ('energy drink', 'BEVERAGES'),
  ('fruit juice', 'BEVERAGES'),
  ('beverages', 'BEVERAGES'),
  ('gin', 'BEVERAGES'),
  ('ginger ale', 'BEVERAGES'),
  ('coffee', 'BEVERAGES'),
  ('coffee beans', 'BEVERAGES'),
  ('coffee pads', 'BEVERAGES'),
  ('coffee capsules', 'BEVERAGES'),
  ('hot chocolate', 'BEVERAGES'),
  ('diet soda', 'BEVERAGES'),
  ('soda', 'BEVERAGES'),
  ('bottled water', 'BEVERAGES'),
  ('orange juice', 'BEVERAGES'),
  ('prosecco', 'BEVERAGES'),
  ('red wine', 'BEVERAGES'),
  ('rum', 'BEVERAGES'),
  ('spirits', 'BEVERAGES'),
  ('smoothie', 'BEVERAGES'),
  ('sports drink', 'BEVERAGES'),
  ('tea', 'BEVERAGES'),
  ('tonic water', 'BEVERAGES'),
  ('vodka', 'BEVERAGES'),
  ('water', 'BEVERAGES'),
  ('white wine', 'BEVERAGES'),
  ('whiskey', 'BEVERAGES'),
  ('cigarettes', 'BEVERAGES'),
  ('ale', 'BEVERAGES'),
  ('garbage bags', 'HOUSEHOLD'),
  ('dishwashing liquid', 'HOUSEHOLD'),
  ('aluminum foil', 'HOUSEHOLD'),
  ('baby food', 'HOUSEHOLD'),
  ('parchment paper', 'HOUSEHOLD'),
  ('bathroom cleaner', 'HOUSEHOLD'),
  ('batteries', 'HOUSEHOLD'),
  ('flowers', 'HOUSEHOLD'),
  ('plastic wrap', 'HOUSEHOLD'),
  ('gift', 'HOUSEHOLD'),
  ('wrapping paper', 'HOUSEHOLD'),
  ('dishwasher salt', 'HOUSEHOLD'),
  ('dishwasher tabs', 'HOUSEHOLD'),
  ('glass cleaner', 'HOUSEHOLD'),
  ('light bulb', 'HOUSEHOLD'),
  ('paper towels', 'HOUSEHOLD'),
  ('candles', 'HOUSEHOLD'),
  ('cleaning supplies', 'HOUSEHOLD'),
  ('sponge', 'HOUSEHOLD'),
  ('napkins', 'HOUSEHOLD'),
  ('toilet cleaner', 'HOUSEHOLD'),
  ('laundry detergent', 'HOUSEHOLD'),
  ('fabric softener', 'HOUSEHOLD'),
  ('pads', 'CARE'),
  ('body lotion', 'CARE'),
  ('conditioner', 'CARE'),
  ('deodorant', 'CARE'),
  ('shower gel', 'CARE'),
  ('wet wipes', 'CARE'),
  ('face cream', 'CARE'),
  ('hair gel', 'CARE'),
  ('hair spray', 'CARE'),
  ('hand cream', 'CARE'),
  ('insect repellent', 'CARE'),
  ('condoms', 'CARE'),
  ('facial tissues', 'CARE'),
  ('contact lens solution', 'CARE'),
  ('lip balm', 'CARE'),
  ('makeup remover', 'CARE'),
  ('mouthwash', 'CARE'),
  ('nail polish', 'CARE'),
  ('nail polish remover', 'CARE'),
  ('bandaids', 'CARE'),
  ('razor', 'CARE'),
  ('razor blades', 'CARE'),
  ('shaving cream', 'CARE'),
  ('pain reliever', 'CARE'),
  ('soap', 'CARE'),
  ('shampoo', 'CARE'),
  ('sunblock', 'CARE'),
  ('tampons', 'CARE'),
  ('tissues', 'CARE'),
  ('vitamins', 'CARE'),
  ('toilet paper', 'CARE'),
  ('cotton pads', 'CARE'),
  ('cotton swabs', 'CARE'),
  ('diapers', 'CARE'),
  ('toothbrush', 'CARE'),
  ('toothpaste', 'CARE'),
  ('dental floss', 'CARE'),
  ('cod liver oil', 'CARE'),
  ('fish food', 'PETS'),
  ('dog food', 'PETS'),
  ('dog treats', 'PETS'),
  ('cat food', 'PETS'),
  ('cat treats', 'PETS'),
  ('cat litter', 'PETS'),
  ('bird food', 'PETS'),
  ('potting soil', 'GARDEN'),
  ('grill', 'GARDEN'),
  ('parasol', 'GARDEN'),
  ('fertilizer', 'GARDEN'),
  ('pots', 'GARDEN'),
  ('garden tool', 'GARDEN'),
  ('seeds', 'GARDEN'),
  ('propane', 'GARDEN'),
  ('charcoal', 'GARDEN'),
  ('nails', 'GARDEN'),
  ('bolts', 'GARDEN'),
  ('brush', 'GARDEN'),
  ('watering can', 'GARDEN'),
  ('plants', 'GARDEN'),
  ('lawnmower', 'GARDEN')
), assignments AS (
  SELECT product.id, COALESCE((
    SELECT catalog.category FROM catalog
    WHERE product."normalizedName" ~ ('\m' || catalog.name || '\M')
    ORDER BY (product."normalizedName" = catalog.name) DESC,
      length(catalog.name) DESC, position(catalog.name IN product."normalizedName") ASC
    LIMIT 1
  ), 'OWN_ITEMS')::"ShoppingCategory" AS category
  FROM "ShoppingProduct" product
)
UPDATE "ShoppingProduct" product SET category = assignments.category
FROM assignments WHERE product.id = assignments.id;

ALTER TABLE "ShoppingProduct" ALTER COLUMN "category" SET NOT NULL;
