-- CreateEnum
CREATE TYPE "OdaTransferStage" AS ENUM ('CHECKING_CART', 'FINDING_PRODUCTS', 'CHOOSING_PRODUCTS', 'ADDING_TO_CART', 'UPDATING_LIST');

-- AlterTable
ALTER TABLE "OdaTransfer" ADD COLUMN     "stage" "OdaTransferStage" NOT NULL DEFAULT 'CHECKING_CART';
