import { ImportRecipeError } from "@planeatrepeat/shared";
import {
  fetchTranscript,
  listLanguages,
  type TranscriptSegment,
} from "youtube-transcript-plus";

import { env } from "~/env";

const VIDEO_DETAILS_TIMEOUT_MS = 10_000;
const CAPTION_LIST_TIMEOUT_MS = 15_000;
const TRANSCRIPT_TIMEOUT_MS = 20_000;
const MIN_USEFUL_DESCRIPTION_LENGTH = 80;
const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36 PlanEatRepeatRecipeImport/1.0";

type YouTubeVideoResponse = {
  items?: Array<{
    snippet?: { title?: string; description?: string };
    contentDetails?: { contentRating?: { ytRating?: string } };
  }>;
};

export const acquireYouTubeRecipeText = async (videoId: string) => {
  const video = await fetchVideo(videoId);
  const transcript = await fetchPreferredTranscript(videoId);
  const description = video.snippet?.description?.trim() ?? "";
  const transcriptText = transcript.map((segment) => segment.text).join(" ");

  if (
    transcriptText.length === 0 &&
    description.length < MIN_USEFUL_DESCRIPTION_LENGTH
  ) {
    throw new ImportRecipeError("NO_RECIPE_FOUND");
  }

  return `YouTube title:\n${video.snippet?.title ?? ""}\n\nYouTube description:\n${description}\n\nCaption transcript:\n${transcriptText}`;
};

const fetchVideo = async (videoId: string) => {
  if (!env.YOUTUBE_API_KEY) {
    throw new ImportRecipeError("FETCH_FAILED");
  }

  try {
    const apiUrl = new URL("https://www.googleapis.com/youtube/v3/videos");
    apiUrl.searchParams.set("part", "snippet,contentDetails");
    apiUrl.searchParams.set("id", videoId);
    apiUrl.searchParams.set("key", env.YOUTUBE_API_KEY);

    const response = await timedFetch(apiUrl, VIDEO_DETAILS_TIMEOUT_MS);
    if (!response.ok) throw new ImportRecipeError("FETCH_FAILED");

    const data = (await response.json()) as YouTubeVideoResponse;
    const video = data.items?.[0];
    if (
      !video?.snippet ||
      video.contentDetails?.contentRating?.ytRating === "ytAgeRestricted"
    ) {
      throw new ImportRecipeError("FETCH_FAILED");
    }

    return video;
  } catch (error) {
    if (error instanceof ImportRecipeError) throw error;
    throw new ImportRecipeError("FETCH_FAILED");
  }
};

const fetchPreferredTranscript = async (
  videoId: string,
): Promise<TranscriptSegment[]> => {
  try {
    const languages = await listLanguages(videoId, {
      userAgent: USER_AGENT,
      signal: AbortSignal.timeout(CAPTION_LIST_TIMEOUT_MS),
    });
    const preferred =
      languages.find((language) => !language.isAutoGenerated) ?? languages[0];
    if (!preferred) return [];

    return await fetchTranscript(videoId, {
      lang: preferred.languageCode,
      userAgent: USER_AGENT,
      signal: AbortSignal.timeout(TRANSCRIPT_TIMEOUT_MS),
    });
  } catch {
    // Written descriptions are sufficient; caption retrieval is best effort.
    return [];
  }
};

const timedFetch = async (url: URL, timeoutMs: number) => {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    return await fetch(url, { signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
};
